name: monitoring

services:
  dozzle:
    image: docker.io/amir20/dozzle:v10.1.0@sha256:17bae4b6cbe93cdfe83efcc146870c43603ef97f8ad920f9945b212d727cc21c
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.middlewares=authelia@docker
      - traefik.http.routers.dozzle.service=dozzle
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges:true

  fluentbit:
    image: docker.io/fluent/fluent-bit:4.2.3@sha256:a5761fa961cb22dd0875883a4d446b1acd99d4935d77358aa9f50ee177e44fe2
    container_name: fluentbit
    volumes:
      - ./config/fluentbit/config.yaml:/fluent-bit/etc/fluent-bit.yaml:ro
      - ${APPS_FOLDER}/monitoring/fluentbit:/fluent-bit/etc/data:ro
      # Logs
      - ${APPS_FOLDER}/network/traefik/logs:/var/log/traefik:ro
    networks:
      metrics_internal:
    command:
      ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.yaml"]
    restart: unless-stopped
    user: 568:568
    security_opt:
      - no-new-privileges:true

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
    container_name: homepage
    volumes:
      - ./config/homepage/widgets.yaml:/app/config/widgets.yaml
      - ./config/homepage/services.yaml:/app/config/services.yaml
      - ./config/homepage/settings.yaml:/app/config/settings.yaml
      - ./config/homepage/bookmarks.yaml:/app/config/bookmarks.yaml
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      HOMEPAGE_ALLOWED_HOSTS: homepage.${DOMAIN}
      HOMEPAGE_VAR_DOMAIN: ${DOMAIN}
    env_file:
      - homepage.env
    networks:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.middlewares=authelia@docker
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges:true

  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.8.6-omnibus@sha256:8dcc722855198da5c198f8b0cdb1b0a33dac7ca91df57bc01fc24052e18ce49f
    container_name: scrutiny
    volumes:
      - /run/udev:/run/udev:ro
      - ${APPS_FOLDER}/monitoring/scrutiny/config:/opt/scrutiny/config
      - ${APPS_FOLDER}/monitoring/scrutiny/data:/opt/scrutiny/influxdb
    networks:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN}`)
      - traefik.http.routers.scrutiny.entrypoints=websecure
      - traefik.http.routers.scrutiny.middlewares=authelia@docker
      - traefik.http.routers.scrutiny.service=scrutiny
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/nvme0
    security_opt:
      - no-new-privileges:true

  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v1.48.0@sha256:2c15cfb7902d3f2756efbdf120dbeabb9dca45457addf32f7071236b4c6feb8e
    container_name: victorialogs
    volumes:
      - ${APPS_FOLDER}/monitoring/victorialogs:/vlogs
    networks:
      metrics_internal:
      traefik:
    command: --storageDataPath=/vlogs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.victorialogs.rule=Host(`victorialogs.${DOMAIN}`)
      - traefik.http.routers.victorialogs.entrypoints=websecure
      - traefik.http.routers.victorialogs.middlewares=authelia@docker
      - traefik.http.routers.victorialogs.service=victorialogs
      - traefik.http.services.victorialogs.loadbalancer.server.port=9428
    user: 568:568
    security_opt:
      - no-new-privileges:true

  vmauth:
    image: docker.io/victoriametrics/vmauth:v1.137.0@sha256:6d715d2dfbcc5b7e4d8148ea11b12238f6a1c1d3bd2c37c2e598638c4fc8ddac
    container_name: vmauth
    depends_on:
      victorialogs:
        condition: service_healthy
    volumes:
      - ./config/vmauth:/etc/vmauth
    networks:
      metrics_internal:
    command: -auth.config=/etc/vmauth/vmauth.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8427/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    user: 568:568
    security_opt:
      - no-new-privileges:true
networks:
  traefik:
    external: true
    name: traefik

  metrics_internal:
    external: false
    name: metrics_internal
    internal: true
