name: monitoring

services:
  crowdsec-ui:
    image: ghcr.io/theduffman85/crowdsec-web-ui:2026.8.3@sha256:bfadbab9a72c21bf906eca0bb9bfb894c28ab31d1aed5bc25d9d9c153903ef89
    container_name: crowdsec_ui
    volumes:
      - ${APPS_FOLDER}/monitoring/crowdsec:/app/data
    environment:
      TZ: Europe/Berlin
      CROWDSEC_URL: http://crowdsec:8080
      CROWDSEC_USER: crowdsec-ui
      CROWDSEC_PASSWORD: ${CROWDSEC_API_KEY}
    networks:
      traefik_internal:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.crowdsec_ui.rule=Host(`crowdsec.${DOMAIN}`)
      - traefik.http.routers.crowdsec_ui.entrypoints=websecure
      - traefik.http.routers.crowdsec_ui.middlewares=authelia@docker
      - traefik.http.routers.crowdsec_ui.service=crowdsec_ui
      - traefik.http.services.crowdsec_ui.loadbalancer.server.port=3000
    user: 568:568
    security_opt:
      - no-new-privileges:true

  dozzle:
    image: ghcr.io/amir20/dozzle:v10.8.0@sha256:243666b0593ff33ed1373901575236f0d6bed8a2d6b451cdae4345969a7b6d5c
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik_internal:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.middlewares=authelia@docker
      - traefik.http.routers.dozzle.service=dozzle
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges:true

  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    container_name: homepage
    volumes:
      - ./config/homepage/widgets.yaml:/app/config/widgets.yaml:ro
      - ./config/homepage/services.yaml:/app/config/services.yaml:ro
      - ./config/homepage/settings.yaml:/app/config/settings.yaml:ro
      - ./config/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      HOMEPAGE_ALLOWED_HOSTS: homepage.${DOMAIN}
      HOMEPAGE_VAR_DOMAIN: ${DOMAIN}
    env_file:
      - homepage.env
    networks:
      monitoring:
      traefik_internal:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.middlewares=authelia@docker
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges:true

  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.9.3-omnibus@sha256:2f3d23edadf6d12f9c26d16808bd8620852a37dd3074e814352a2328d48fccb0
    container_name: scrutiny
    volumes:
      - /run/udev:/run/udev:ro
      - ${APPS_FOLDER}/monitoring/scrutiny/config:/opt/scrutiny/config
      - ${APPS_FOLDER}/monitoring/scrutiny/data:/opt/scrutiny/influxdb
    networks:
      traefik_internal:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN}`)
      - traefik.http.routers.scrutiny.entrypoints=websecure
      - traefik.http.routers.scrutiny.middlewares=authelia@docker
      - traefik.http.routers.scrutiny.service=scrutiny
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/nvme0
    security_opt:
      - no-new-privileges:true

networks:
  monitoring:
    external: false
    name: monitoring
  traefik_internal:
    external: true
    name: traefik_internal
