name: media

services:
  # todo: add bazarr-uhd
  bazarr:
    image: lscr.io/linuxserver/bazarr:version-v1.6.0@sha256:84b6f05a7a4194fafe5a0bec062d32f6ae9ea74db33d43d678cb9a3191f31c24
    container_name: bazarr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}/media:/data/media
      - ${APPS_FOLDER}/media/bazarr:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.middlewares=authelia@docker
      - traefik.http.routers.bazarr.service=bazarr
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    security_opt:
      - no-new-privileges:true

  configarr:
    image: ghcr.io/raydak-labs/configarr:1.32.0@sha256:8a94c8355f86619ac4c52298144f15859f9c66311515f96c4688435fa020039e
    container_name: configarr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ./config/configarr/config.yml:/app/config/config.yml:ro
      - ${APPS_FOLDER}/media/configarr:/app/repos
    environment:
      TZ: Europe/Berlin
      RADARR_API_KEY: ${RADARR_API_KEY}
      RADARR_UHD_API_KEY: ${RADARR_UHD_API_KEY}
      SONARR_API_KEY: ${SONARR_API_KEY}
      SONARR_UHD_API_KEY: ${SONARR_UHD_API_KEY}
      SABNZBD_API_KEY: ${SABNZBD_API_KEY}
      QBITTORRENT_API_KEY: ${QBITTORRENT_API_KEY}
      WHISPARR_API_KEY: ${WHISPARR_API_KEY}
      CONFIGARR_ENABLE_MERGE: true
    network_mode: service:gluetun
    restart: no
    user: 568:568
    profiles:
      - manual

  gluetun:
    image: ghcr.io/qdm12/gluetun:v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027
    container_name: gluetun
    volumes:
      - ${APPS_FOLDER}/media/gluetun:/gluetun
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      UPDATER_PERIOD: 24h
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}'
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WG_PRIV_KEY}
      WIREGUARD_ADDRESSES: ${WG_ADDRESS}
      SERVER_COUNTRIES: Switzerland
      OWNED_ONLY: yes
      BLOCK_MALICIOUS: off
    networks:
      media:
      traefik_internal:
      auth_internal:
        ipv4_address: 172.31.254.5
        ipv6_address: fdd0:0:0:fff::5
    extra_hosts:
      - "lldap:172.31.254.4"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    hostname: media

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:version-12.1ubu2604@sha256:51252e7a416e703cdc3cd91e8a54673a2430cc80409be8a38abe511411577b95
    container_name: jellyfin
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}/media:/data/media
      - ${APPS_FOLDER}/media/jellyfin:/config
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - no-new-privileges:true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:version-2.6.5.5623@sha256:c96b56d94d116a9f4de94bc23d3381689492e6c3cfb7435320e8d982e406f99a
    container_name: prowlarr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${APPS_FOLDER}/media/prowlarr:/config
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      PROWLARR__AUTH__METHOD: External
      PROWLARR__AUTH__APIKEY: ${PROWLARR_API_KEY}
      PROWLARR__LOG__LEVEL: info
      PROWLARR__LOG__ANALYTICSENABLED: False
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN:?err}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.middlewares=authelia@docker
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    security_opt:
      - no-new-privileges:true

  radarr:
    image: lscr.io/linuxserver/radarr:version-6.4.4.10685@sha256:adb6c09d6b729ea5e642c99cea35af72702ef476bf4763f153299ac5db9f0b4f
    container_name: radarr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/radarr:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      RADARR__AUTH__METHOD: External
      RADARR__AUTH__APIKEY: ${RADARR_API_KEY}
      RADARR__LOG__LEVEL: info
      RADARR__LOG__ANALYTICSENABLED: False
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.middlewares=authelia@docker
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    security_opt:
      - no-new-privileges:true

  radarr-uhd:
    image: lscr.io/linuxserver/radarr:version-6.4.4.10685@sha256:adb6c09d6b729ea5e642c99cea35af72702ef476bf4763f153299ac5db9f0b4f
    container_name: radarr-uhd
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/radarr-uhd:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      RADARR__AUTH__METHOD: External
      RADARR__AUTH__APIKEY: ${RADARR_UHD_API_KEY}
      RADARR__LOG__LEVEL: info
      RADARR__LOG__ANALYTICSENABLED: False
      RADARR__SERVER__PORT: 7879
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-uhd.rule=Host(`radarr-uhd.${DOMAIN}`)
      - traefik.http.routers.radarr-uhd.entrypoints=websecure
      - traefik.http.routers.radarr-uhd.middlewares=authelia@docker
      - traefik.http.routers.radarr-uhd.service=radarr-uhd
      - traefik.http.services.radarr-uhd.loadbalancer.server.port=7879
    security_opt:
      - no-new-privileges:true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:version-5.1.3@sha256:948ea3dc45d68943ec14b33ba37ffa1488da3e9837bf3ca0f75621e971614d85
    container_name: sabnzbd
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${APPS_FOLDER}/media/sabnzbd:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.middlewares=authelia@docker
      - traefik.http.routers.sabnzbd.service=sabnzbd
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges:true

  seerr:
    image: ghcr.io/hotio/seerr:release-v3.4.1@sha256:0b3935e54f85d12d2dd8573bbf9fc64c60d773899ce164a84abd3e1c9d2e6f74
    container_name: seerr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${APPS_FOLDER}/media/seerr:/app/config
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      API_KEY: ${SEERR_API_KEY}
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.seerr.rule=Host(`seerr.${DOMAIN}`)
      - traefik.http.routers.seerr.entrypoints=websecure
      - traefik.http.routers.seerr.service=seerr
      - traefik.http.services.seerr.loadbalancer.server.port=5055
    security_opt:
      - no-new-privileges:true

  sonarr:
    image: lscr.io/linuxserver/sonarr:version-4.0.19.2979@sha256:82172b363f9eddc02aca544f880a044f2ceb9aaf190bc87e4454e2f705eb91d0
    container_name: sonarr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/sonarr:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      SONARR__AUTH__METHOD: External
      SONARR__AUTH__APIKEY: ${SONARR_API_KEY}
      SONARR__LOG__LEVEL: info
      SONARR__LOG__ANALYTICSENABLED: False
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.middlewares=authelia@docker
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    security_opt:
      - no-new-privileges:true

  sonarr-uhd:
    image: lscr.io/linuxserver/sonarr:version-4.0.19.2979@sha256:82172b363f9eddc02aca544f880a044f2ceb9aaf190bc87e4454e2f705eb91d0
    container_name: sonarr-uhd
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/sonarr-uhd:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      SONARR__AUTH__METHOD: External
      SONARR__AUTH__APIKEY: ${SONARR_UHD_API_KEY}
      SONARR__LOG__LEVEL: info
      SONARR__LOG__ANALYTICSENABLED: False
      SONARR__SERVER__PORT: 8988
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-uhd.rule=Host(`sonarr-uhd.${DOMAIN}`)
      - traefik.http.routers.sonarr-uhd.entrypoints=websecure
      - traefik.http.routers.sonarr-uhd.middlewares=authelia@docker
      - traefik.http.routers.sonarr-uhd.service=sonarr-uhd
      - traefik.http.services.sonarr-uhd.loadbalancer.server.port=8988
    security_opt:
      - no-new-privileges:true

  stash:
    image: ghcr.io/hotio/stash:release-v0.31.1@sha256:7207ddaa08af81b7d6e1b300dfb071ad8cd56e3272af4dfcdbae2a3a364edfea
    container_name: stash
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}/media:/data/media
      - ${APPS_FOLDER}/media/stash:/config
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      #STASH_STASH: /data/media/adult
      STASH_PORT: 9998
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.stash.rule=Host(`stash.${DOMAIN}`)
      - traefik.http.routers.stash.entrypoints=websecure
      - traefik.http.routers.stash.middlewares=authelia@docker
      - traefik.http.routers.stash.service=stash
      - traefik.http.services.stash.loadbalancer.server.port=9998
    security_opt:
      - no-new-privileges:true

  thelounge:
    image: ghcr.io/lordbex/thelounge:4.8.10@sha256:08c109fba2749e356dcc40b3864c7a1bf75c84c1be38494463bf835b85111886
    container_name: thelounge
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${APPS_FOLDER}/media/thelounge:/var/opt/thelounge
    environment:
      TZ: Europe/Berlin
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.thelounge.rule=Host(`thelounge.${DOMAIN}`)
      - traefik.http.routers.thelounge.entrypoints=websecure
      - traefik.http.routers.thelounge.service=thelounge
      - traefik.http.services.thelounge.loadbalancer.server.port=9000
    user: 568:568
    security_opt:
      - no-new-privileges:true

  whisparr:
    image: ghcr.io/hotio/whisparr:v3-v3.5.0@sha256:48e2ca62d786b5d26e156bfc62da8ed3e98c1ef0f4da7557a1759ba0ed2c021d
    container_name: whisparr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/whisparr:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      WHISPARR__AUTH__METHOD: External
      WHISPARR__AUTH__APIKEY: ${WHISPARR_API_KEY}
      WHISPARR__LOG__LEVEL: info
      WHISPARR__LOG__ANALYTICSENABLED: False
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whisparr.rule=Host(`whisparr.${DOMAIN}`)
      - traefik.http.routers.whisparr.entrypoints=websecure
      - traefik.http.routers.whisparr.middlewares=authelia@docker
      - traefik.http.routers.whisparr.service=whisparr
      - traefik.http.services.whisparr.loadbalancer.server.port=6969
    security_opt:
      - no-new-privileges:true

  whisparr2:
    image: ghcr.io/hotio/whisparr:v2-v2.2.0@sha256:0044747ffbfd8f0bdb7571d902e043425100cb890df07b24f9c3e1d8c5e9c092
    container_name: whisparr2
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${APPS_FOLDER}/media/whisparr2:/config
      - ${APPS_FOLDER}/media/usenet:/data/usenet
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      WHISPARR__AUTH__METHOD: External
      WHISPARR__AUTH__APIKEY: ${WHISPARR_API_KEY}
      WHISPARR__LOG__LEVEL: info
      WHISPARR__LOG__ANALYTICSENABLED: False
      WHISPARR__SERVER__PORT: 6968
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whisparr2.rule=Host(`whisparr2.${DOMAIN}`)
      - traefik.http.routers.whisparr2.entrypoints=websecure
      - traefik.http.routers.whisparr2.middlewares=authelia@docker
      - traefik.http.routers.whisparr2.service=whisparr2
      - traefik.http.services.whisparr2.loadbalancer.server.port=6968
    security_opt:
      - no-new-privileges:true

networks:
  media:
    external: false
    name: media
  traefik_internal:
    external: true
    name: traefik_internal
  auth_internal:
    external: true
    name: auth_internal
