name: nextcloud

services:
  collabora:
    image: docker.io/collabora/code:25.04.9.2.1@sha256:cfbf62dbed7f3a2bebeb634235c606613813a1857f85111da3a97db316029bba
    container_name: collabora
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      password: ${COLLABORA_PASSWORD}
      username: ${COLLABORA_USERNAME}
      aliasgroup1: https://nextcloud.${DOMAIN}:443,http://nextcloud:80
      server_name: collabora.${DOMAIN}
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.termination=true \
        --o:logging.level=warning \
        --o:logging.level_startup=warning \
        --o:welcome.enable=false \
        --o:remote_font_config.url=https://nextcloud.${DOMAIN}/apps/richdocuments/settings/fonts.json \
    networks:
      nextcloud:
      traefik:
    command: ["coolconfig generate-proof-key && /start-collabora-online.sh"]
    entrypoint: ["/bin/bash", "-c"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9980/hosting/discovery"]
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.collabora.rule=Host(`collabora.${DOMAIN}`)
      - traefik.http.routers.collabora.entrypoints=websecure,websecure-pub
      - traefik.http.routers.collabora.service=collabora
      - traefik.http.services.collabora.loadbalancer.server.port=9980
    cap_add:
      - MKNOD
      - SYS_ADMIN
      - SYS_CHROOT
      - FOWNER
      - CHOWN

  mariadb:
    image: docker.io/library/mariadb:11.8.6@sha256:8164f184d16c30e2f159e30518113667b796306dff0fe558876ab1ff521a682f
    container_name: nextcloud-db
    volumes:
      - ${APPS_FOLDER}/nextcloud/db:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    networks:
      nextcloud:
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: unless-stopped
    user: 568:568

  nextcloud:
    image: docker.io/library/nextcloud:33.0.0@sha256:ff2cbaab14c85e587b5541e3aff4216a8a484e06424ebae661581937c0c8da0c
    container_name: nextcloud
    depends_on:
      - collabora
      - mariadb
      - redis
      - nextcloud-whiteboard
    volumes:
      - ${CONTENT_FOLDER}/files:/var/www/html/data
      - ${APPS_FOLDER}/nextcloud/app:/var/www/html
      - ${APPS_FOLDER}/nextcloud/redis/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini
      # Logs
      - ${APPS_FOLDER}/nextcloud/logs:/var/log/nextcloud
    environment:
      TZ: Europe/Berlin
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      TRUSTED_PROXIES: 172.31.255.0/24 fdd0:0:0:1000::/64
      OVERWRITEHOST: nextcloud.${DOMAIN}
      OVERWRITECLIURL: https://nextcloud.${DOMAIN}
      OVERWRITEPROTOCOL: https
      NC_serverid: 1
    networks:
      nextcloud:
      traefik:
      auth_internal:
        ipv4_address: 172.31.254.6
        ipv6_address: fdd0:0:0:fff::6
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.routers.nextcloud.entrypoints=websecure,websecure-pub
      - traefik.http.routers.nextcloud.service=nextcloud
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    user: 568:568

  nextcloud-whiteboard:
    image: ghcr.io/nextcloud-releases/whiteboard:v1.5.7@sha256:4ca6103eeab072c010b1d7acb04e0af08d48b1f6f53b0328c4180a40ae5d89ad
    container_name: nextcloud-whiteboard
    environment:
      TZ: Europe/Berlin
      NEXTCLOUD_URL: https://nextcloud.${DOMAIN}
      JWT_SECRET_KEY: ${WHITEBOARD_SECRET}
    networks:
      nextcloud:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.nextcloud-whiteboard.rule=Host(`whiteboard.${DOMAIN}`)
      - traefik.http.routers.nextcloud-whiteboard.entrypoints=websecure,websecure-pub
      - traefik.http.routers.nextcloud-whiteboard.service=nextcloud-whiteboard
      - traefik.http.services.nextcloud-whiteboard.loadbalancer.server.port=3002
    user: 568:568

  redis:
    image: docker.io/library/redis:8.6.1-alpine@sha256:2afba59292f25f5d1af200496db41bea2c6c816b059f57ae74703a50a03a27d0
    container_name: nextcloud-redis
    networks:
      nextcloud:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

networks:
  nextcloud:
    external: false
    name: nextcloud
  traefik:
    external: true
    name: traefik
  auth_internal:
    external: true
    name: auth_internal
