name: immich

services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    volumes:
      - ${APPS_FOLDER}/immich/db:/var/lib/postgresql/data
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    networks:
      immich:
    restart: unless-stopped
    user: 568:568
    security_opt:
      - no-new-privileges:true
    shm_size: 128mb

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6@sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556
    container_name: immich_machine_learning
    volumes:
      - ${APPS_FOLDER}/immich/model-cache:/cache
      - ${APPS_FOLDER}/immich/model-dotcache:/.cache
      - ${APPS_FOLDER}/immich/model-config:/.config
    environment:
      TZ: Europe/Berlin
    networks:
      immich:
    restart: unless-stopped
    user: 568:568
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
    container_name: immich_server
    depends_on:
      - database
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTENT_FOLDER}/images:/data
    environment:
      TZ: Europe/Berlin
      IMMICH_TRUSTED_PROXIES: 172.31.255.0/24,fdd0:0:0:1000::/64
    env_file:
      - .env
    networks:
      immich:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.service=immich
      # - traefik.http.routers.immich-pub.rule=Host(`immich.${DOMAIN}`)
      # - traefik.http.routers.immich-pub.entrypoints=websecure-pub
      # TODO: add header auth middleware for pub router
      # - traefik.http.routers.immich-pub.service=immich
      - traefik.http.services.immich.loadbalancer.server.port=2283
    user: 568:568
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  redis:
    image: docker.io/valkey/valkey:9.0.2-alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2
    container_name: immich_redis
    networks:
      immich:
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    security_opt:
      - no-new-privileges:true

networks:
  immich:
    external: false
    name: immich
  traefik:
    external: true
    name: traefik
