name: torrent

services:
  autobrr:
    image: ghcr.io/autobrr/autobrr:v1.81.0@sha256:491e3e1a81fe5ced6b542621e49985d0dea58d23257684b0b19d881761736303
    container_name: autobrr
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${APPS_FOLDER}/torrent/autobrr:/config
    environment:
      TZ: Europe/Berlin
      AUTOBRR__LOG_LEVEL: INFO
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.autobrr.rule=Host(`autobrr.${DOMAIN}`)
      - traefik.http.routers.autobrr.entrypoints=websecure
      - traefik.http.routers.autobrr.middlewares=authelia@docker
      - traefik.http.routers.autobrr.service=autobrr
      - traefik.http.services.autobrr.loadbalancer.server.port=7474
    user: 568:568
    security_opt:
      - no-new-privileges:true

  gluetun:
    image: ghcr.io/qdm12/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: torrent-gluetun
    volumes:
      - ${APPS_FOLDER}/torrent/gluetun:/gluetun
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      UPDATER_PERIOD: 0
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}'
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WG_PRIV_KEY}
      SERVER_COUNTRIES: Switzerland
      BLOCK_MALICIOUS: off
    networks:
      torrent:
      traefik_internal:
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    hostname: torrent

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-v5.2.3@sha256:26689d60b283a8d026965e7d9a0c941f4c168fbe1af028b31e9db42ce6aa357b
    container_name: qbittorrent
    volumes:
      - ${MEDIA_FOLDER}/torrent:/data/torrent
      - ${APPS_FOLDER}/torrent/qbittorrent:/config
    environment:
      PUID: 568
      PGID: 568
      TZ: Europe/Berlin
      WEBUI_PORTS: 8080/tcp
      LIBTORRENT: v2
      VPN_ENABLED: true
      VPN_CONF: wg0
      VPN_PROVIDER: proton
      VPN_AUTO_PORT_FORWARD: true
      VPN_HEALTHCHECK_ENABLED: true
    networks:
      torrent:
      traefik_internal:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.middlewares=authelia@docker
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true

  qui:
    image: ghcr.io/autobrr/qui:v1.22.0@sha256:5d4f98d973129edc3ac04a2b74e3e791c86c5c92ef4d5dae64622be000578e80
    container_name: qui
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${MEDIA_FOLDER}/torrent:/data/torrent
      - ${APPS_FOLDER}/torrent/qui:/config
    environment:
      TZ: Europe/Berlin
      QUI__AUTH_DISABLED: true
      QUI__I_ACKNOWLEDGE_THIS_IS_A_BAD_IDEA: true
      QUI__AUTH_DISABLED_ALLOWED_CIDRS: 172.31.255.0/24,fdd0:0:0:1000::/64
    network_mode: service:gluetun
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qui.rule=Host(`qui.${DOMAIN}`)
      - traefik.http.routers.qui.entrypoints=websecure
      - traefik.http.routers.qui.middlewares=authelia@docker
      - traefik.http.routers.qui.service=qui
      - traefik.http.services.qui.loadbalancer.server.port=7476
    user: 568:568
    security_opt:
      - no-new-privileges:true

networks:
  torrent:
    external: false
    name: torrent
  traefik_internal:
    external: true
    name: traefik_internal
